### ISSUE TITLE
Could not open input file: ./bin/magento-php

### ISSUE THREAD

**Issue by ghost** [ojhaujjwal/magedock#1]
I have a problem when execute command line docker-compose exec workspace magento-installer
After I enter admin password and choose yes for use sample data.
It show:
Running Magento 2 setup script...
Could not open input file: ./bin/magento-php
The setup script has completed execution.

**Comment by PaoloFalomo** [comment]
@vothanhliem1994it i did a pull request for fixing this
https://github.com/ojhaujjwal/magedock/pull/3

**Comment by PaoloFalomo** [comment]
@vothanhliem1994it the pull request has been accepted by @ojhaujjwal so this issue might be closed

**Comment by ojhaujjwal** [comment]
thanks very much @PaoloFalomo much appreciated.
I think I forgot the issue unfortunately. thanks for covering me up :D
